config/routes.rb
Sagha::Application.routes.draw do
  resources :demanda_videomonitoramentos

  resources :treinamentos_ti

  resources :outras_informacoes

  resources :orcamentos_ti

  resources :videomonitoramentos

  resources :informacao_sites

  resources :projetos_ti

  resources :informacoes_ged

  resources :servidores

  resources :orgao_sistemas_proprios

  resources :orgao_sistemas

  resources :sistemas

  resources :orgao_equipamentos

  resources :equipamentos

  resources :orgao_impressoras
  resources :cargos

  resources :informacoes_pessoais

  resources :orgao_softwares

  resources :desktops

  resources :softwares
  resources :orgaos

  devise_for :users

  resources :admin do
    collection do
      get 'add_user'
    end
  end

  root :to => "home#index"

  get 'inicial', to: 'home#index', as: :index

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/desktop.rb
class Desktop < ActiveRecord::Base
  belongs_to :orgao
end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base
end

app/models/informacao_ged.rb
class InformacaoGed < ActiveRecord::Base
  belongs_to :orgao
end

app/models/informacao_site.rb
class InformacaoSite < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orcamento_ti.rb
class OrcamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao.rb
class Orgao < ActiveRecord::Base
  has_many :users
end

app/models/orgao_impressora.rb
class OrgaoImpressora < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao_sistema.rb
class OrgaoSistema < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :sistema
end

app/models/orgao_software.rb
class OrgaoSoftware < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :software
end

app/models/outra_informacao.rb
class OutraInformacao < ActiveRecord::Base
  belongs_to :orgao
end

app/models/projeto_ti.rb
class ProjetoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
  belongs_to :orgao
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
end

app/models/software.rb
class Software < ActiveRecord::Base
end

app/models/treinamento_ti.rb
class TreinamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :orgao
end

app/controllers/orgao_impressoras_controller.rb
# encoding: utf-8

class OrgaoImpressorasController < ApplicationController
  before_action :set_orgao_impressora, only: [:show, :edit, :update, :destroy]

  # GET /orgao_impressoras
  # GET /orgao_impressoras.json
  def index
    if !params[:orgao_id].blank? && current_user.admin
      @orgao_impressoras = OrgaoImpressora.where(orgao_id: params[:orgao_id])
    elsif current_user.admin
      @orgao_impressoras = OrgaoImpressora.all
    else
      @orgao_impressoras = OrgaoImpressora.where(orgao_id: current_user.orgao_id)
    end
  end

  # GET /orgao_impressoras/1
  # GET /orgao_impressoras/1.json
  def show
  end

  # GET /orgao_impressoras/new
  def new
    @orgao_impressora = OrgaoImpressora.new
  end

  # GET /orgao_impressoras/1/edit
  def edit
  end

  # POST /orgao_impressoras
  # POST /orgao_impressoras.json
  def create
    @orgao_impressora = OrgaoImpressora.new(orgao_impressora_params)

    respond_to do |format|
      if @orgao_impressora.save
        format.html { redirect_to @orgao_impressora, notice: 'Órgão impressora criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @orgao_impressora }
      else
        format.html { render action: 'new' }
        format.json { render json: @orgao_impressora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgao_impressoras/1
  # PATCH/PUT /orgao_impressoras/1.json
  def update
    respond_to do |format|
      if @orgao_impressora.update(orgao_impressora_params)
        format.html { redirect_to @orgao_impressora, notice: 'Órgão impressora atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @orgao_impressora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgao_impressoras/1
  # DELETE /orgao_impressoras/1.json
  def destroy
    @orgao_impressora.destroy
    respond_to do |format|
      format.html { redirect_to orgao_impressoras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orgao_impressora
      @orgao_impressora = OrgaoImpressora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orgao_impressora_params
      params.require(:orgao_impressora).permit(:orgao_id, :tipo, :funcionando, :defeituosas, :detalhes_defeituosas, :extras, :emprestadas, :detalhes_emprestadas, :proprias, :alugadas, :em_garantia, :tem_contrato_locacao, :tem_contrato_manutencao, :detalhes_contrato_manutencao, :detalhes_contrato_locacao)
    end
end

app/helpers/desktops_helper.rb
module DesktopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/orgao_impressoras/_filtro.html.haml
= form_tag({controller: :orgao_impressoras, action: :index}, method: "get") do
  = select_tag :orgao_id, options_from_collection_for_select(Orgao.all, :id, :nome), :prompt => "Selecione um órgão", class: 'span6'
  
  = submit_tag :submit, class: 'btn btn-success filtro', value: 'Filtrar órgão'

app/views/orgao_impressoras/_form.html.haml
= simple_form_for(@orgao_impressora) do |f|
  = f.error_notification

  .inputs
    %div{style: "display: block;"}
      - if current_user.admin
        = f.association :orgao, :required => true, input_html: {class: 'span6 no-margin flat-select', style: "display: block;"}, label_method: :nome, label_html: {style: "display: block;"}, label: 'Órgão', selected: current_user.orgao_id
      - else
        = f.input :orgao_id, as: :hidden, input_html: {value: current_user.orgao_id}
    = f.input :tipo, as: :select, collection: ['Matricial', 'Jato de Tinta', 'Laser', 'Plotter', 'Térmica'], input_html: {class: 'span6 no-margin', style: "display: block;"}, label_html: {style: "display: block;"}, prompt: 'Escolha o tipo'
    = f.input :funcionando, input_html: { class: 'span6' }
    = f.input :defeituosas, input_html: { class: 'span6' }
    = f.input :detalhes_defeituosas, placeholder: "Descreva os detalhes das peças defeituosas", :input_html => {:rows => 4, :cols => 25, :class => 'input-textarea'}
    = f.input :extras, input_html: { class: 'span6' }
    = f.input :emprestadas, input_html: { class: 'span6' }
    = f.input :detalhes_emprestadas, placeholder: "Descreva os detalhes das peças emprestadas", :input_html => {:rows => 4, :cols => 25, :class => 'input-textarea'}
    = f.input :proprias, input_html: { class: 'span6' }, label: 'Próprias'
    = f.input :alugadas, input_html: { class: 'span6' }
    = f.input :em_garantia, input_html: { class: 'span6' }
    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.check_box :tem_contrato_locacao, data: {toggle: 'checkbox'}
      tem contrato de locação?
    = f.input :detalhes_contrato_locacao, placeholder: "Detalhes sobre o contrato de locação", label: 'Detalhes do contrato de locação', :input_html => {:rows => 4, :cols => 25, :class => 'input-textarea'}

    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.check_box :tem_contrato_manutencao, data: {toggle: 'checkbox'}
      tem contrato de manutenção?

    = f.input :detalhes_contrato_manutencao, placeholder: "Detalhes sobre o contrato de manutenção", label: 'Detalhes do contrato de manutenção', :input_html => {:rows => 4, :cols => 25, :class => 'input-textarea'}

  .actions
    = f.button :submit, class: 'btn btn-success', value: 'Cadastrar impressoras'

app/views/orgao_impressoras/edit.html.haml
%h1 Editar registro de impressora

= render 'form'

.btn.btn-small.btn-inverse
  = link_to 'Mostrar', @orgao_impressora

.btn.btn-small.btn-inverse
  = link_to 'Voltar', orgao_impressoras_path

app/views/orgao_impressoras/index.html.haml
%h1 Informações sobre impressoras

- if current_user.admin
  = render 'filtro'

%table.table.table-hover
  %thead
    %tr
      %th Órgão
      %th Tipo
      %th Funcionando
      %th Defeituosas
      %th
      %th
      %th
  %tbody
  - @orgao_impressoras.each do |orgao_impressora|
    %tr
      %td= orgao_impressora.orgao.nome if orgao_impressora.orgao
      %td= orgao_impressora.tipo
      %td= orgao_impressora.funcionando
      %td= orgao_impressora.defeituosas
      %td
        = link_to orgao_impressora, :title => 'Visualizar' do
          %span.fui-eye{:class => 'icons24'}
      %td
        = link_to edit_orgao_impressora_path(orgao_impressora), :title => 'Editar' do
          %span.fui-new{:class => 'icons24'}
      %td 
        = link_to orgao_impressora, :method => :delete, :title => 'Excluir', :data => { :confirm => 'Você tem certeza?' } do
          %span.fui-cross{:class => 'icons24'}

%br

- if not current_user.admin
  .btn.btn-small.btn-inverse
    = link_to 'Novo registro', new_orgao_impressora_path

app/views/orgao_impressoras/new.html.haml
%h1 Novo registro de impressora

= render 'form'

= link_to 'Voltar', orgao_impressoras_path

app/views/orgao_impressoras/show.html.haml
%p.alert.alert-success= notice

%h1 Visualizar impressora selecionada

%table.table.table-hover

  %tr
    %td
      %b Órgão:
    %td
      = @orgao_impressora.orgao_id
  %tr
    %td
      %b Tipo:
    %td
      = @orgao_impressora.tipo
  %tr
    %td
      %b Funcionando:
    %td
      = @orgao_impressora.funcionando
  %tr
    %td
      %b Defeituosas:
    %td
      = @orgao_impressora.defeituosas
  %tr
    %td
      %b Detalhes defeituosas:
    %td
      = @orgao_impressora.detalhes_defeituosas
  %tr
    %td
      %b Extras:
    %td
      = @orgao_impressora.extras
  %tr
    %td
      %b Emprestadas:
    %td
      = @orgao_impressora.emprestadas
  %tr
    %td
      %b Detalhes emprestadas:
    %td
      = @orgao_impressora.detalhes_emprestadas
  %tr
    %td
      %b Próprias:
    %td
      = @orgao_impressora.proprias
  %tr
    %td
      %b Alugadas:
    %td
      = @orgao_impressora.alugadas
  %tr
    %td
      %b Em garantia:
    %td
      = @orgao_impressora.em_garantia
  %tr
    %td
      %b Tem contrato locação:
    %td
      = @orgao_impressora.tem_contrato_locacao
  %tr
    %td
      %b Tem contrato manutenção:
    %td
      = @orgao_impressora.tem_contrato_manutencao
  %tr
    %td
      %b Detalhes contrato manutenção:
    %td
      = @orgao_impressora.detalhes_contrato_manutencao
  %tr
    %td
      %b Detalhes contrato locação:
    %td
      = @orgao_impressora.detalhes_contrato_locacao

.btn.btn-small.btn-inverse
  = link_to 'Editar', edit_orgao_impressora_path(@orgao_impressora)

.btn.btn-small.btn-inverse
  = link_to 'Voltar', orgao_impressoras_path