config/routes.rb
Sagha::Application.routes.draw do
  resources :demanda_videomonitoramentos

  resources :treinamentos_ti

  resources :outras_informacoes

  resources :orcamentos_ti

  resources :videomonitoramentos

  resources :informacao_sites

  resources :projetos_ti

  resources :informacoes_ged

  resources :servidores

  resources :orgao_sistemas_proprios

  resources :orgao_sistemas

  resources :sistemas

  resources :orgao_equipamentos

  resources :equipamentos

  resources :orgao_impressoras
  resources :cargos

  resources :informacoes_pessoais

  resources :orgao_softwares

  resources :desktops

  resources :softwares
  resources :orgaos

  devise_for :users

  resources :admin do
    collection do
      get 'add_user'
    end
  end

  root :to => "home#index"

  get 'inicial', to: 'home#index', as: :index

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/desktop.rb
class Desktop < ActiveRecord::Base
  belongs_to :orgao
end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base
end

app/models/informacao_ged.rb
class InformacaoGed < ActiveRecord::Base
  belongs_to :orgao
end

app/models/informacao_site.rb
class InformacaoSite < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orcamento_ti.rb
class OrcamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao.rb
class Orgao < ActiveRecord::Base
  has_many :users
end

app/models/orgao_impressora.rb
class OrgaoImpressora < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao_sistema.rb
class OrgaoSistema < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :sistema
end

app/models/orgao_software.rb
class OrgaoSoftware < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :software
end

app/models/outra_informacao.rb
class OutraInformacao < ActiveRecord::Base
  belongs_to :orgao
end

app/models/projeto_ti.rb
class ProjetoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
  belongs_to :orgao
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
end

app/models/software.rb
class Software < ActiveRecord::Base
end

app/models/treinamento_ti.rb
class TreinamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :orgao
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  before_action :set_sistema, only: [:show, :edit, :update, :destroy]

  # GET /sistemas
  # GET /sistemas.json
  def index
    @sistemas = Sistema.all
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
  end

  # GET /sistemas/new
  def new
    @sistema = Sistema.new
  end

  # GET /sistemas/1/edit
  def edit
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
    @sistema = Sistema.new(sistema_params)

    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: 'Sistema criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @sistema }
      else
        format.html { render action: 'new' }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sistemas/1
  # PATCH/PUT /sistemas/1.json
  def update
    respond_to do |format|
      if @sistema.update(sistema_params)
        format.html { redirect_to @sistema, notice: 'Sistema atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
    @sistema.destroy
    respond_to do |format|
      format.html { redirect_to sistemas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sistema
      @sistema = Sistema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sistema_params
      params.require(:sistema).permit(:nome)
    end
end

app/helpers/desktops_helper.rb
module DesktopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/sistemas/_form.html.haml
= simple_form_for(@sistema) do |f|
  = f.error_notification

  .inputs
    = f.input :nome, label: 'Nome do sistema', input_html: { class: 'span6' }

  .actions
    = f.button :submit, class: 'btn btn-success', value: 'Cadastrar Sistema'

app/views/sistemas/edit.html.haml
%h1 Editar sistema

= render 'form'


.btn.btn-small.btn-inverse
  = link_to 'Mostrar', @sistema
  
.btn.btn-small.btn-inverse
  = link_to 'Voltar', sistemas_path

app/views/sistemas/index.html.haml
%h1 Listar sistemas cadastrados

%table.table.table-hover
  %thead
    %tr
      %th Nome
      %th
      %th
      %th
  %tbody
  - @sistemas.each do |sistema|
    %tr
      %td= sistema.nome
      %td
        = link_to sistema, :title => 'Visualizar' do
          %span.fui-eye{:class => 'icons24'}
      %td
        = link_to edit_sistema_path(sistema), :title => 'Editar' do
          %span.fui-new{:class => 'icons24'}
      %td 
        = link_to sistema, :method => :delete, :title => 'Excluir', :data => { :confirm => 'Você tem certeza?' } do
          %span.fui-cross{:class => 'icons24'}      

%br

.btn.btn-small.btn-inverse
  = link_to 'Novo Sistema', new_sistema_path

app/views/sistemas/new.html.haml
%h1 Cadastrar novo sistema

= render 'form'

= link_to 'Voltar', sistemas_path

app/views/sistemas/show.html.haml
%p.alert.alert-success= notice

%h1 Visualizar sistema selecionado

%table.table.table-hover
  %tr
    %td
      %b Nome:
    %td
      = @sistema.nome

%br

.btn.btn-small.btn-inverse
  = link_to 'Edit', edit_sistema_path(@sistema)

.btn.btn-small.btn-inverse
  = link_to 'Back', sistemas_path