config/routes.rb
Sagha::Application.routes.draw do
  resources :demanda_videomonitoramentos

  resources :treinamentos_ti

  resources :outras_informacoes

  resources :orcamentos_ti

  resources :videomonitoramentos

  resources :informacao_sites

  resources :projetos_ti

  resources :informacoes_ged

  resources :servidores

  resources :orgao_sistemas_proprios

  resources :orgao_sistemas

  resources :sistemas

  resources :orgao_equipamentos

  resources :equipamentos

  resources :orgao_impressoras
  resources :cargos

  resources :informacoes_pessoais

  resources :orgao_softwares

  resources :desktops

  resources :softwares
  resources :orgaos

  devise_for :users

  resources :admin do
    collection do
      get 'add_user'
    end
  end

  root :to => "home#index"

  get 'inicial', to: 'home#index', as: :index

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/desktop.rb
class Desktop < ActiveRecord::Base
  belongs_to :orgao
end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base
end

app/models/informacao_ged.rb
class InformacaoGed < ActiveRecord::Base
  belongs_to :orgao
end

app/models/informacao_site.rb
class InformacaoSite < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orcamento_ti.rb
class OrcamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao.rb
class Orgao < ActiveRecord::Base
  has_many :users
end

app/models/orgao_impressora.rb
class OrgaoImpressora < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao_sistema.rb
class OrgaoSistema < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :sistema
end

app/models/orgao_software.rb
class OrgaoSoftware < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :software
end

app/models/projeto_ti.rb
class ProjetoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
  belongs_to :orgao
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
end

app/models/software.rb
class Software < ActiveRecord::Base
end

app/models/treinamento_ti.rb
class TreinamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :orgao
end

app/helpers/desktops_helper.rb
module DesktopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/admin/_form.html.haml
= simple_form_for(@user, :url => admin_path(@user)) do |f|
  = f.error_notification

  .inputs
    = f.input :email, :required => true, :autofocus => true, input_html: { class: 'span6' }
    = f.association :orgao, :required => true, input_html: {class: 'select-block'}, label_method: :nome, :label => "Órgão", input_html: {class: 'span6 no-margin', style: "display: block;"}, label_html: {style: "display: block;"}, prompt: "Selecione uma opção"
    = f.input :password, :required => false, :label => "Senha", input_html: { class: 'span6' }
    = f.input :password_confirmation, :required => false, :label => "Confirme sua senha", input_html: { class: 'span6' }
    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.input :admin, :label => "Administrador do sistema?", :required => false
  
  .actions
    = f.button :submit, class: 'btn btn-success', value: 'Cadastrar Usuário'

app/views/admin/add_user.html.haml
%h2 Cadastrar novo usuário
= simple_form_for(@user, :url => admin_index_path) do |f|
  = f.error_notification
  .form-inputs
    = f.input :email, :required => true, :autofocus => true, input_html: { class: 'span6' }

    = f.association :orgao, :required => true, input_html: {class: 'select-block'}, label_method: :nome, :label => "Órgão", input_html: {class: 'span6 no-margin', style: "display: block;"}, label_html: {style: "display: block;"}, prompt: "Selecione uma opção"
    = f.input :password, :required => true, :label => "Senha", input_html: { class: 'span6' }

    = f.input :password_confirmation, :required => true, :label => "Confirme sua senha", input_html: { class: 'span6' }

    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.input :admin, :label => "Administrador do sistema?"  

  .form-actions
    = f.button :submit, "Cadastrar", class: 'btn btn-success'

app/views/admin/edit.html.haml
%h1 Editar usuário

= render 'form'

.btn.btn-small.btn-inverse
  = link_to 'Voltar', admin_index_path

app/views/admin/index.html.haml
%h1 Listar usuários cadastrados

%table.table.table-hover
  %thead
    %tr
      %th Email
      %th Órgao
      %th
      %th
  %tbody
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.orgao.nome if user.orgao
      %td
        = link_to edit_admin_path(user), :title => 'Editar' do
          %span.fui-new{:class => 'icons24'}
      %td 
        = link_to admin_path(user), :method => :delete, :title => 'Excluir', :data => { :confirm => 'Você tem certeza?' } do
          %span.fui-cross{:class => 'icons24'}

%br

.btn.btn-small.btn-inverse
  = link_to 'Novo usuário', add_user_admin_index_path

app/views/admin/show.html.haml
%p.alert.alert-success= notice

%h1 Visualizar usuário selecionado

%table.table.table-hover
  %tr
    %td
      %b Email:
    %td
      = @user.email
  %tr
    %td
      %b Órgão:
    %td
      = @user.orgao.nome
  %tr
    %td
      %b É administrador?
    %td
      = @user.admin      
%br      

.btn.btn-small.btn-inverse
  = link_to 'Voltar', admin_index_path