config/routes.rb
Sagha::Application.routes.draw do
  resources :demanda_videomonitoramentos

  resources :treinamentos_ti

  resources :outras_informacoes

  resources :orcamentos_ti

  resources :videomonitoramentos

  resources :informacao_sites

  resources :projetos_ti

  resources :informacoes_ged

  resources :servidores

  resources :orgao_sistemas_proprios

  resources :orgao_sistemas

  resources :sistemas

  resources :orgao_equipamentos

  resources :equipamentos

  resources :orgao_impressoras
  resources :cargos

  resources :informacoes_pessoais

  resources :orgao_softwares

  resources :desktops

  resources :softwares
  resources :orgaos

  devise_for :users

  resources :admin do
    collection do
      get 'add_user'
    end
  end

  root :to => "home#index"

  get 'inicial', to: 'home#index', as: :index

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
end

app/models/desktop.rb
class Desktop < ActiveRecord::Base
  belongs_to :orgao
end

app/models/equipamento.rb
class Equipamento < ActiveRecord::Base
end

app/models/informacao_ged.rb
class InformacaoGed < ActiveRecord::Base
  belongs_to :orgao
end

app/models/informacao_site.rb
class InformacaoSite < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orcamento_ti.rb
class OrcamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao.rb
class Orgao < ActiveRecord::Base
  has_many :users
end

app/models/orgao_impressora.rb
class OrgaoImpressora < ActiveRecord::Base
  belongs_to :orgao
end

app/models/orgao_sistema.rb
class OrgaoSistema < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :sistema
end

app/models/orgao_software.rb
class OrgaoSoftware < ActiveRecord::Base
  belongs_to :orgao
  belongs_to :software
end

app/models/projeto_ti.rb
class ProjetoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
  belongs_to :orgao
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
end

app/models/software.rb
class Software < ActiveRecord::Base
end

app/models/treinamento_ti.rb
class TreinamentoTi < ActiveRecord::Base
  belongs_to :orgao
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :orgao
end

app/controllers/informacoes_ged_controller.rb
# encoding: utf-8

class InformacoesGedController < ApplicationController
  before_action :set_informacao_ged, only: [:show, :edit, :update, :destroy]

  # GET /informacoes_ged
  # GET /informacoes_ged.json
  def index
    if !params[:orgao_id].blank? && current_user.admin
      @informacoes_ged = InformacaoGed.where(orgao_id: params[:orgao_id])
    elsif current_user.admin
      @informacoes_ged = InformacaoGed.all
    else
      @informacoes_ged = InformacaoGed.where(orgao_id: current_user.orgao_id)
    end    
    #@informacoes_ged = InformacaoGed.all
  end

  # GET /informacoes_ged/1
  # GET /informacoes_ged/1.json
  def show
  end

  # GET /informacoes_ged/new
  def new
    @informacao_ged = InformacaoGed.new
  end

  # GET /informacoes_ged/1/edit
  def edit
  end

  # POST /informacoes_ged
  # POST /informacoes_ged.json
  def create
    @informacao_ged = InformacaoGed.new(informacao_ged_params)

    respond_to do |format|
      if @informacao_ged.save
        format.html { redirect_to @informacao_ged, notice: 'Informação sobre o GED criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @informacao_ged }
      else
        format.html { render action: 'new' }
        format.json { render json: @informacao_ged.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /informacoes_ged/1
  # PATCH/PUT /informacoes_ged/1.json
  def update
    respond_to do |format|
      if @informacao_ged.update(informacao_ged_params)
        format.html { redirect_to @informacao_ged, notice: 'Informação sobre o GED atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @informacao_ged.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /informacoes_ged/1
  # DELETE /informacoes_ged/1.json
  def destroy
    @informacao_ged.destroy
    respond_to do |format|
      format.html { redirect_to informacoes_ged_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_informacao_ged
      @informacao_ged = InformacaoGed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def informacao_ged_params
      params.require(:informacao_ged).permit(:orgao_id, :processo_digitalizacao, :numero_digitalizacao, :documentos_indexados, :hospedado_sepog)
    end
end

app/helpers/desktops_helper.rb
module DesktopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/informacoes_ged_helper.rb
module InformacoesGedHelper
end

app/helpers/orgaos_helper.rb
module OrgaosHelper
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/informacoes_ged/_filtro.html.haml
= form_tag({controller: :informacoes_ged, action: :index}, method: "get") do
  = select_tag :orgao_id, options_from_collection_for_select(Orgao.all, :id, :nome), :prompt => "Selecione um órgão", class: 'span6'
  
  = submit_tag :submit, class: 'btn btn-success filtro', value: 'Filtrar órgão'

app/views/informacoes_ged/_form.html.haml
= simple_form_for(@informacao_ged) do |f|
  = f.error_notification

  .inputs
    %div{style: "display: block;"}
      - if current_user.admin
        = f.association :orgao, :required => true, input_html: {class: 'span6 no-margin flat-select', style: "display: block;"}, label_method: :nome, label_html: {style: "display: block;"}, label: 'Órgão', selected: current_user.orgao_id
      - else
        = f.input :orgao_id, as: :hidden, input_html: {value: current_user.orgao_id}
    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.input :processo_digitalizacao, label: 'O Órgão possui algum processo de Digitalização dos documentos?'
    = f.input :numero_digitalizacao, input_html: { class: 'span6' }, label: 'Qual a % de documentos digitalizados do Órgão?', placeholder: "Coloque apenas o número"
    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.input :documentos_indexados, label: 'Os documentos digitalizados estão devidamente indexados?'
    %label.checkbox
      %span.icons
        %span.first-icon.fui-checkbox-unchecked
        %span.second-icon.fui-checkbox-checked
      = f.input :hospedado_sepog, label: 'Os arquivos digitalizados foram hospedados no Servidor da SEPOG (antiga SAM)?'

  .actions
    = f.button :submit, class: 'btn btn-success', value: 'Cadastrar Informação sobre GED'

app/views/informacoes_ged/edit.html.haml
%h1 Editar Informações sobre o GED

= render 'form'

.btn.btn-small.btn-inverse
  = link_to 'Mostrar', @informacao_ged

.btn.btn-small.btn-inverse
  = link_to 'Voltar', informacoes_ged_path

app/views/informacoes_ged/index.html.haml
%h1 Listar Informações sobre o GED

- if current_user.admin
  = render 'filtro'
  
%table.table.table-hover
  %thead
    %tr
      %th Órgão
      %th Possui algum processo de Digitalização dos documentos?
      %th Qual a % de documentos digitalizados?
      %th
      %th
      %th
  %tbody
  - @informacoes_ged.each do |informacao_ged|
    %tr
      %td= informacao_ged.orgao.nome if informacao_ged.orgao
      %td= informacao_ged.processo_digitalizacao
      %td= informacao_ged.numero_digitalizacao
      %td
        = link_to informacao_ged, :title => 'Visualizar' do
          %span.fui-eye{:class => 'icons24'}
      %td
        = link_to edit_informacao_ged_path(informacao_ged), :title => 'Editar' do
          %span.fui-new{:class => 'icons24'}
      %td 
        = link_to informacao_ged, :method => :delete, :title => 'Excluir', :data => { :confirm => 'Você tem certeza?' } do
          %span.fui-cross{:class => 'icons24'}

%br

- if not current_user.admin
  .btn.btn-small.btn-inverse
    = link_to 'Nova Informação GED', new_informacao_ged_path

app/views/informacoes_ged/new.html.haml
%h1 Nova informação sobre GED

= render 'form'

= link_to 'Voltar', informacoes_ged_path

app/views/informacoes_ged/show.html.haml
%p.alert.alert-success= notice

%h1 Visualizar informação sobre o GED

%table.table.table-hover
  %tr
    %td
      %b Órgão
    %td
      = @informacao_ged.orgao_id  
  %tr
    %td
      %b O Órgão possui algum processo de Digitalização dos documentos?
    %td
      = @informacao_ged.processo_digitalizacao
  %tr
    %td
      %b Qual a % de documentos digitalizados do Órgão?
    %td
      = @informacao_ged.numero_digitalizacao
  %tr
    %td
      %b Os documentos digitalizados estão devidamente indexados?
    %td
      = @informacao_ged.documentos_indexados
  %tr
    %td
      %b Os arquivos digitalizados foram hospedados no Servidor da SEPOG (antiga SAM)?
    %td
      = @informacao_ged.hospedado_sepog

%br

.btn.btn-small.btn-inverse
  = link_to 'Editar', edit_informacao_ged_path(@informacao_ged)

.btn.btn-small.btn-inverse
  = link_to 'Voltar', informacoes_ged_path